# Generated by Django 3.2 on 2021-04-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_posts_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=''),
        ),
    ]
